- hosts: localhost
  pre_tasks:
  - name: Update Apt
    become: true
    apt:
      force_apt_get: true
      update_cache: true
      state: present
    tags:
      - install
      - core
  tasks:
    - include_tasks: tasks/core.yml
    - include_tasks: tasks/zsh.yml
    - include_tasks: tasks/nvim.yml
    - include_tasks: tasks/dotfiles.yml
    - include_tasks: tasks/productivity.yml
