- name: Install ZSH
  apt: name=zsh
  tags: &zsh_tasks [ 'install', 'productivity', 'dotfiles', 'zsh' ]

# - name: Change shell to zsh
#   shell: chsh -s $(which zsh)
#   tags: *zsh_tasks

- name: Check if oh-my-zsh is already installed
  stat:
    path: /home/mcaragheorghe/.oh-my-zsh
  register: oh_my_stats
  tags: *zsh_tasks

- name: Install Oh-My-Zsh
  shell: curl -L https://raw.github.com/robbyrussell/oh-my-zsh/master/tools/install.sh > ~/.oh-my-installer && chmod +x ~/.oh-my-installer && ~/.oh-my-installer
  tags: *zsh_tasks
  when: oh_my_stats.stat.exists == False
  become_user: mcaragheorghe

